### ISSUE TITLE
繪圖工具諮詢

### ISSUE THREAD

**Issue by AceCoooool** [victoresque/MLDS2018SPRING#1]
你好，諮詢下您在Report裏面關於model的圖是用什麼軟件畫的呢？謝謝～

**Comment by victoresque** [comment]
Hi，model 部分如果指的是 hw3 中的圖，

是使用 draw.io 繪制，網址爲 https://www.draw.io/

但其實大部分仍是手工，和使用 visio 等工具差不多，謝謝！

Best,
Victor

**Comment by AceCoooool** [comment]
謝謝！謝謝！～其實我自己也用draw.io，只是看到你畫的更好，所以諮詢一下～ 非常感謝～
