### ISSUE TITLE
Use gpu in HW4-1

### ISSUE THREAD

**Issue by ByronHsu** [victoresque/MLDS2018SPRING#2]
In my experiment, although the most time-consuming part is the game engine, using gpu to train can accelerate the process a lot!
BTW, your coding style is really elegant and clear. I learned a lot from here :)

**Comment by victoresque** [comment]
Hi, Byron

Thanks for the advice, I'll try it out!

If you're interested in the coding style we used in this repo,
you may also check out my PyTorch template for deep learning projects:
https://github.com/victoresque/pytorch-template

Cheers,
Victor

**Comment by ByronHsu** [comment]
I am really a big fan of pytorch-template. Thanks for your dedication on that project!
